export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';
export const GET_PRODUCTS_SUCCEED = 'GET_PRODUCTS_SUCCEED';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const POST_PRODUCT_REQUESTED = 'POST_PRODUCT_REQUESTED';
export const POST_PRODUCT_SUCCEED = 'POST_PRODUCT_SUCCEED';
export const POST_PRODUCT_FAIL = 'POST_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUESTED = 'DELETE_PRODUCT_REQUESTED';
export const DELETE_PRODUCT_SUCCEED = 'DELETE_PRODUCT_SUCCEED';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_REQUESTED = 'UPDATE_PRODUCT_REQUESTED';
export const UPDATE_PRODUCT_SUCCEED = 'UPDATE_PRODUCT_SUCCEED';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';